const LIST = {
    REQUEST: "URL_LIST_REQUEST",
    SUCCESS: "URL_LIST_SUCCESS",
    ERROR: "URL_LIST_ERROR",
    RESET: "URL_LIST_RESET",
  };
  
  const ADD = {
    REQUEST: "URL_ADD_REQUEST",
    SUCCESS: "URL_ADD_SUCCESS",
    ERROR: "URL_ADD_ERROR",
    RESET: "URL_ADD_RESET",
  };
  
  const DELETE = {
    REQUEST: "URL_DELETE_REQUEST",
    SUCCESS: "URL_DELETE_SUCCESS",
    ERROR: "URL_DELETE_ERROR",
    RESET: "URL_DELETE_RESET",
  };
  
  const DETAILS = {
    REQUEST: "URL_DETAILS_REQUEST",
    SUCCESS: "URL_DETAILS_SUCCESS",
    ERROR: "URL_DETAILS_ERROR",
    RESET: "URL_DETAILS_RESET",
  };
  
  const EDIT = {
    REQUEST: "URL_EDIT_REQUEST",
    SUCCESS: "URL_EDIT_SUCCESS",
    ERROR: "URL_EDIT_ERROR",
    RESET: "URL_EDIT_RESET",
  };

  const REDIRECT = {
    REQUEST: "URL_REDIRECT_REQUEST",
    SUCCESS: "URL_REDIRECT_SUCCESS",
    ERROR: "URL_REDIRECT_ERROR",
    RESET: "URL_REDIRECT_RESET",
  };

  export const UrlActionTypes = {
    URL_LIST: LIST,
    ADD: ADD,
    DELETE: DELETE,
    DETAILS: DETAILS,
    EDIT: EDIT,
    REDIRECT : REDIRECT
  };